### ISSUE TITLE
Dominus Maniple lacking Mech Knights

### ISSUE THREAD

**Issue by Baldrick-Dogsbody** [BSData/at-2018#14]
The Dominus Maniple allows you to use either Questoris or Cerastus Knights, but there is no way to add the Mechanicum variants (Magaera, Styrix, Atropos)

The fix should be easy, and should be capable of being added to both the NR and BS repos.

**Comment by jorisvangestel** [comment]
The traitor book specifically names only Questoris and Cerastus knights as options for that maniple, unless there is a change somewhere else I'm missing?
