### ISSUE TITLE
Open topics from old repo

### ISSUE THREAD

**Issue by BoaPi** [BSData/at-2018#2]
## What is this about

This issue sums up open topics from old issues form the old [Adeptus Titanicus repo](https://github.com/BSData/adeptus-titanicus)

#### Legio Specifics
* [x] Legio Vulcanum - Janus upgrade for Warmaster Apocalypse Missile Array
* [x] Legio Infernus - Dark Blessing (increased maxiumum mutation, requires the mutation system to be implemented)
* [ ] ~~Legio Audax - Ursus Claws, Add Impale rule~~
* [x] Legio Magna Wargear
  * [x] Directed Pressure Outlet (Adds 3" to the weapon’s Short Range)
    * [x] Suzerain Class Plasma Destructor
    * [x] Melta Cannon (Warmaster Shoulder)
    * [x] Krius Siege Drill
    * [x] Melta Cannon (Reaver)
* [x] Legio Vulturum Wargear
  * [x] Storm Frag Shells
    * [x] Vulcan mega-bolter (WH)
    * [x] Vulcan mega-bolter (RVR)
    * [x] Vulcan mega-bolter Array (WL)
    * [x] Vulcan mega-bolter Array (WM)

#### Traitor Wargear Options
* [x] Corrosive Payload (applies to all weapons that have Ordnance or Rapid traits so will require some work)
  * [x] Revelator Missile Launcher
  * [x] Krius Grav Imploder
  * [x] Cruciator Gatling Array
  * [x] Macro-gatling Blaster
  * [x] Paired Gatling Blasters
  * [x] Gatling Blaster
  * [x] Vulcan Mega-bolter
    * [x] Warmaster
    * [x] Warlord
    * [x] Reaver
    * [x] Warhound
* [x] Focused Capacitors (applies to all weapons that have Maximal Fire trait so will require some work)
  * [x] Suzerain Class Plasma Destructor
  * [x] Sunfury Plasma Annihilator
  * [x] Plasma Blastgun
    * [x] Warhound
    * [x] Warmaster

#### Battlegroup Tweaks
* [ ] ~~Personal Trait: Superior Tactician~~
* [x] Quake cannon nerf
* [x] Directed Pressure Outlet
* [ ] ~~Vanguard Fighters~~
* [ ] ~~Personal Trait: Spear of Tigrus~~
* [ ] ~~Legio Specific Wargear - Devotional War Sirens~~
* [ ] ~~Legio Trait: Veteran Princeps~~
* [ ] ~~Legio Trait: Seizing the Initiative~~
* [x] Legio Specific Wargear: Infernus Missiles
* [ ] ~~Legio Trait: Righteous Fire~~
* [x] Legio Specific Stratagem: Fog of War (1)
* [ ] ~~Legio Specific Wargear: Bi-folded Power Containment~~
* [ ] ~~Legio Trait: Lost Sons~~
* [ ] ~~Legio Specific Personal Traits: Broken by Treachery~~
* [ ] ~~Legio Specific Personal Traits: Soldier of the Crusade~~
* [x] Auxiliary Knight Banner
* [ ] ~~Maniples: Lupercal Light Maniple, Maniple Trait,Hunting Pack~~

#### Knight Household Tweaks
* [ ] ~~Household Specific Knightly Qualities, Blackhearted~~

**Comment by jorisvangestel** [comment]
Went through the Battlegroup and Knight Household tweaks list, everything that's strikken through was already up to date, for the others I made the necessary changes. Not quite sure what the 'Quake cannon nerf' was, it was only missing a few traits (maybe the rest was already applied).
