### ISSUE TITLE
[Anon] Battlegroup: Legio Audax is not available to be chosen

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/at-2018#28]
**Problem:**
Legio Audax is not available to be chosen

**Expected:**
Legio Audax can be chosen and the reaver can be replaced by a direwolf

 **Additional Info:**
the heavy scout titan rule.

**List:** https://www.newrecruit.eu/app/list/VlSTm
**Unit:** Venator Light Maniple, id: 5192-e107-566f-52c7

**Comment by jorisvangestel** [comment]
This is a duplicate of #23
