### ISSUE TITLE
[Anon] Battlegroup: Legio Audax unavailable as an option in these specific maniples.

### ISSUE THREAD

**Issue by NewRecruitAnon** [BSData/at-2018#31]
**Problem:**
Legio Audax unavailable as an option in these specific maniples.

**Expected:**
Audax is able to field these maniples, provided the single mandatory Reaver is replaced with a Direwolf.

 **Additional Info:**
Direwolf "Heavy Scout Titan" rule provides the restrictions when fielded in Audax

**List:** https://www.newrecruit.eu/app/list/uAQES

**Comment by jorisvangestel** [comment]
This is a duplicate of #23
