### ISSUE TITLE
Legio specific entries (wargear and princep traits) appearing across maniples on multiple maniple lists

### ISSUE THREAD

**Issue by BoaPi** [BSData/at-2018#4]
## What is this issue about

If I have two or more maniples with different Legios selected then princep traits and legio specific wargear appear in both maniples.

**To Reproduce**
1. craete a battlegroupe
2. add two maniples to the batlegroup
3. add a different legio with wargear to each maniple
4. legio specific wargear is now visible in both maniples from both legios

**Expected behavior**
only legio specific wargear is showing up in each legio

**additional notes**
* work in progress #1 
* **WON'T FIX #7**

**Comment by BoaPi** [comment]
@jorisvangestel we can close this here, right?

**Comment by jorisvangestel** [comment]
Uh, yeah I suppose so, we still need to fix the princeps traits appearing across maniples but we can turn that into a separate issue.
