### ISSUE TITLE
Legio specific wargear inconsistencies

### ISSUE THREAD

**Issue by BoaPi** [BSData/at-2018#7]
There are some inconsistencies with how Legio Specific Wargear works in some cases. There are some upgrades that are specific to weapons (e.g. infector static rounds, infernus clinging phosphex). Some of these upgrades have been implemented as an option for the weapon (like infector static rounds), but others are still just listed under the wargear section even though they are also a specific upgrade for a weapon (like the infernus phosphex).

All these wargear upgrades that are actually weapon specific should be make an upgrade to the weapon to make it consistent across the board, it probably also requires a double check with the rules from the new Legio/Traitor books as some of the wordings have been changes (e.g. infector static rounds changes from a single upgrade in DoM to one that needs to be bought per weapon in the newest books).

Universal wargear:
* [x] Hardened Casing

Loyalist wargear:
* [x] Hunter shells

Traitor wargear:
* [x] Corrosive Payload

Legio wargear:
* [ ] #9
* [x] Accelerated Autoloaders
* [x] Blind Missiles
* [x] Clinging Phosphex
* [x] Diabatic Warheads
* [x] Earthbreaker Missiles
* [x] Fusion Missiles
* [x] Janus Pattern Missiles
* [x] Macro Charges
* [x] Macro Magazines
* [x] Maglock Shells
* [x] Radiative Warheads
* [x] Seismic Auspex
* [x] Static Rounds

**Comment by BoaPi** [comment]
seismic auspex is a good example for it or earthquaker missiles from legio krytos.

**Comment by jorisvangestel** [comment]
Yeah I think we where unable to properly do the validation before. With NR's proper unit scoped validation we should be able to fix this pretty easily!
