### ISSUE TITLE
Enhance & Clean-up Categories

### ISSUE THREAD

**Issue by BoaPi** [BSData/at-2018#8]
Instead of having only a category "Blast (x)", there should be a different ones for each possible Blast size, e.g. Blast 3 & Blast 5.

This will also help on assigning the correct Legion Specific Wargear and costs to weapons.

Additionally we should remove categories that a present two times.

**Comment by jorisvangestel** [comment]
I found and removed a lot of duplicate LegioX categories, so that part is fixed. I can see Mordaxis has some weapon that reference the blast (x) category, as well as crusade macro charges. Macro charges changes blast 3 to 5, so I guess that is one we need to apply this. Are there any others?

**Comment by BoaPi** [comment]
have not found so far any other, but the obvious ones where the legioX. Great to see this cleaned up.

For the blast etc., after I have worked on the "Focused Capacitors", we might not need those additional categories. The moment we move a wargear upgrade to the specific weapon it is affecting, things gets way easier. 

So for now I would suggest do nothing here and continue move wargear weapon upgrades to weapons.

**Comment by jorisvangestel** [comment]
Alright, if we run into a weapon upgrade that requires the separate blast things we can do it at that time, The rest is fixed so closing this issue.
