### ISSUE TITLE
Crusade Wargear - Autoloader cost calculation

### ISSUE THREAD

**Issue by BoaPi** [BSData/at-2018#9]
The point cost calculation for the Crusade Wargear Autoloader is tricky.
Initially the cost is 5 points plus the base cost of the weapon. The upgrade can be purchased multiple times. 
For each instance the point cost raises by 10.

### Group 1
* [x]  Warp Missile Support Rack
* when upgraded with Vortex Payload no autoloader is allowed

### Group 2
* [x] Apocalypse missile launchers
* [x] Apocalypse missile laucher
* [x] Multiple Warhead Launchers

### Group 3
* [x] Revelator Missile Launcher
* when upgraded with Corrosive Payload no autoloader is allowed

**Comment by BoaPi** [comment]
as of now, we should implement each possible point cost as one modifier. The use of the repeat modifier is probably to complicated.

**Comment by jorisvangestel** [comment]
To further complicate this, the upgrade 'Multiple Warheards' changes the base cost of the weapon and interacts with the cost of Autoloaders.

**Comment by BoaPi** [comment]
absolutely, I think collecting all possible upgrades is necessary beforehand and than implementing each with fixed costs. As of now I would suggest up to three times the upgrade maybe?
